server {
    listen 8080;
    server_name localhost;

    # EXERCÍCIO 2: Limite do tamanho do corpo da requisição (2MB)
    client_max_body_size 2M;

    # EXERCÍCIO 1: Bloco /status-nginx com JSON 200 direto no Nginx
    location /status-nginx {
        default_type application/json;
        return 200 '{"status": "OK", "mensagem": "Nginx operando sem passar pelo Node.js"}';
    }

    # PASSO 5: Rota de Proxy Reverso para o Express na porta 3006
    location /api/v1/proxy/ {
        proxy_pass http://127.0.0.1:3006;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
