events {
    worker_connections 1024;
}

http {
    # Redireciona logs e arquivos temporários para a sua pasta de usuário
    access_log ~/binario_tech/aula20/nginx_local/access.log;
    error_log ~/binario_tech/aula20/nginx_local/error.log;
    client_body_temp_path ~/binario_tech/aula20/nginx_local/client_body;
    proxy_temp_path ~/binario_tech/aula20/nginx_local/proxy_temp;
    fastcgi_temp_path ~/binario_tech/aula20/nginx_local/fastcgi_temp;
    uwsgi_temp_path ~/binario_tech/aula20/nginx_local/uwsgi_temp;
    scgi_temp_path ~/binario_tech/aula20/nginx_local/scgi_temp;

    server {
        listen 8080;
        server_name localhost;

        # EXERCÍCIO 2: Limite de tamanho de corpo (2 Megabytes)
        client_max_body_size 2M;

        # EXERCÍCIO 1: Bloco /status-nginx com JSON 200 direto do Nginx
        location /status-nginx {
            default_type application/json;
            return 200 '{"status": "OK", "mensagem": "Nginx operando sem passar pelo Node.js"}';
        }

        # PASSO 5: Rota de Proxy Reverso para a API Node.js (porta 3001)
        location /api/v1/proxy/ {
            proxy_pass http://127.0.0.1:3001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'keep-alive';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
